// flow-typed signature: eac456e0fbce4b8e59b554e045633fff
// flow-typed version: <<STUB>>/import-from_v2.1.0/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'import-from'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'import-from' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'import-from/index' {
  declare module.exports: $Exports<'import-from'>;
}
declare module 'import-from/index.js' {
  declare module.exports: $Exports<'import-from'>;
}
