// flow-typed signature: c8b392cc53b91936f5ac2a00e4d12256
// flow-typed version: <<STUB>>/promise-retry_v1.1.1/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'promise-retry'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'promise-retry' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'promise-retry/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'promise-retry/index' {
  declare module.exports: $Exports<'promise-retry'>;
}
declare module 'promise-retry/index.js' {
  declare module.exports: $Exports<'promise-retry'>;
}
declare module 'promise-retry/test/test.js' {
  declare module.exports: $Exports<'promise-retry/test/test'>;
}
